---
title: "README"
---

Scripts in this directory update the objects in `data/`.

```{r}
library(here)
library(SummarizedExperiment)
library(tidyverse)
library(lubridate)
library(magrittr)
```

```{r}
library(tidyverse); library(here); library(magrittr)
source(here("R", "functions.R"))
## inst/extdata/manifest.rds was copied from this location: ovarian.internals/output/03-manifest.rmd/manifest.rds
file <- here("inst", "extdata", "manifest.rds")
manifest0 <- readRDS(file)
## ASSUME THE TUMOR SAMPLE IS ANNOTATED CORRECTLY
manifest2 <- subject_id2(manifest0)
sfile <- here("inst", "extdata", "sdat.rds")
sdat <- read_sdata(sfile)
cdat2 <- clean_clinical_data(sdat, manifest2)
manifest.list <- clean_manifest(manifest2, cdat2)
facets.file <- file.path("..", "output", "facets",
                         "merge-facets-tables.R",
                         "all-segments.txt")
facets <- read_facets(facets.file)
facets.dir <- file.path("..", "output", "facets-trellis/jhpce_directories")
directory.listing <- fs::dir_ls(facets.dir, type="directory")
##trace(join_with_facets, browser)
manifest8 <- join_with_facets(manifest.list, facets, directory.listing)
discordant <- filter(manifest8, discordant_tumor_type)
manifest <- filter_discordant_tumors(manifest8)
clinical <- filter(cdat2, lab_id %in% manifest$lab_id)
save(clinical, file=here("data", "clinical.rda"))
save(manifest, file=here("data", "manifest.rda"))
save(discordant, file=here("data", "discordant.rda"))
check_ids(clinical, manifest)
```

```{r}
##source("manifest.R")
source("idat.endometrioid.R")
source("idat.gi.R")
source("idat.mucinous.R")
source("methylation_se.R")
source("methylation.R")
```

